### Buscar todas as categorias
GET http://localhost:3000/categorias

### Buscar categoria por ID
GET http://localhost:3000/categorias/1

### Criar nova categoria
POST http://localhost:3000/categorias
Content-Type: application/json

{
  "nome": "Lívia",
  "descricao": "Sua aluna favorita"
}

### Atualizar categoria
PUT http://localhost:3000/categorias/1
Content-Type: application/json

{
  "nome": "Tech Atualizado",
  "descricao": "Nova descrição"
}

### Deletar categoria
DELETE http://localhost:3000/categorias/1